language: clojure
lein: 2.7.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  - openjdk7
script:
  - lein with-profile +dev:+1.9 test
jobs:
  include:
    - stage: deploy
      jdk: oraclejdk8
      script: skip
      deploy:
        provider: script
        script: ./deploy-snapshot.sh
        on:
          branch: master
