language: clojure
lein: 2.8.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8
script: lein with-profile +dev:+1.8 test
jobs:
  include:
    - stage: coverage
      jdk: oraclejdk8
      script:
        - lein cloverage --codecov
        - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
    - stage: deploy
      jdk: oraclejdk8
      script: skip
      deploy:
        provider: script
        script: ./deploy-snapshot.sh
        on:
          branch: master
