language: clojure
lein: 2.9.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
before_install: if [ -f "${JAVA_HOME}/lib/security/cacerts" -a -w  "${JAVA_HOME}/lib/security/cacerts" ]; then rm "${JAVA_HOME}/lib/security/cacerts" && ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi
script: lein with-profile +dev:+1.8:+1.10 test
jobs:
  include:
    - stage: coverage
      jdk: openjdk8
      script:
        - lein cloverage --codecov
        - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
    - stage: deploy
      jdk: openjdk8
      script: skip
      deploy:
        provider: script
        script: ./deploy-snapshot.sh
        on:
          branch: master
